version: '3'
services:
  app:
    container_name: golang_container
    environment:
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=product
      - DB_SCHEMA=public
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8000:8080
    volumes:
      - go_app:/app
    depends_on:
      - postgresdb


  postgresdb:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  go_app:
  local_pgdata:
